### PR TITLE
Added the CODEOWNERS file

### PR DESCRIPTION
**Pull request by Harsh-Kapoorr**
# Description

I have been asked to add the CODEOWNERS file into the existing repository and I have added it here perfectly using git bash command line.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by Harsh-Kapoorr — COMMENTED** [review]
Added a fresh code again of CODEOWNERS

**Review by Harsh-Kapoorr — COMMENTED** [review]
@vanessa-cooper
Make it run please this time as I have changed the file

**Review by Harsh-Kapoorr — COMMENTED** [review]
@vanessa-cooper

**Pull request closed without merging**
